Repository csusmGDSC/csusmgdsc-api, pull requests merged in 2025-01, with the labels that each got.

#15 Update Crypto Package to Address Vulnerability
  go.mod
  go.sum
Labels: bug

#18 Update Codebase to Singleton ConfigLoad
  config/config.go
  internal/auth/auth_handler.go
  internal/auth/jwt.go
  internal/handlers/user_handler.go
Labels: help wanted

#21 feat: Add OAuth2 providers: Github, Google
  .env.test
  cmd/main.go
  config/config.go
  internal/auth/auth_handler.go
  internal/auth/jwt.go
  internal/auth/oauth.go
  internal/models/user.go
  routes/routes.go
Labels: enhancement

#24 feat: Add docker containerization for hosting backend api
  .gitignore
  Dockerfile
Labels: enhancement

#29 Refactor Auth handling to Auth package rather than user handlers
  cmd/main.go
  internal/auth/auth.go
  internal/auth/auth_handler.go
  internal/auth/auth_handlers/auth_handler.go
  internal/auth/auth_handlers/handler.go
  internal/auth/auth_middleware/auth_middleware.go
  internal/auth/auth_models/refresh_token.go
  internal/auth/auth_models/user.go
  internal/auth/auth_repositories/refresh_tokens.go
  internal/auth/auth_repositories/user_repo.go
  internal/auth/auth_utils/jwt.go
  internal/auth/auth_utils/oauth.go
  internal/auth/auth_utils/traditional_auth.go
  internal/handlers/user_handler.go
  internal/handlers/user_handler_test.go
  internal/models/user.go
  routes/routes.go
Labels: enhancement

#30 Update Registration Flow
  internal/auth/auth_handlers/auth_handler.go
  internal/auth/auth_models/oauth_register.go
  internal/auth/auth_models/traditional_register.go
  internal/auth/auth_models/user.go
  internal/auth/auth_repositories/user_repo.go
  internal/auth/auth_utils/oauth.go
  internal/auth/auth_utils/traditional_auth.go
  internal/models/user.go
Labels: enhancement

#31 Update OAuth Callback to Redirect to Frontend
  internal/auth/auth_handlers/auth_handler.go
Labels: enhancement

#34 feat: Update event handler and model
  internal/db/repositories/event_repo.go
  internal/models/event.go
Labels: bug

#35 User Getters!
  internal/auth/auth_handlers/auth_handler.go
  internal/auth/auth_models/user.go
  internal/auth/auth_repositories/user_repo.go
  internal/handlers/event_handler.go
  internal/handlers/user_handler.go
  routes/routes.go
Labels: enhancement

#37 Add GET Routes for Events
  internal/db/repositories/event_repo.go
  internal/handlers/event_handler.go
  internal/models/event.go
  routes/routes.go
Labels: enhancement

#32 Feature: Added cors policy for frontend URL. Added fallback to localhost.
  cmd/main.go
  config/config.go
Labels: enhancement

#38 Continious Deployment Github Action
  .github/workflows/docker-publish.yml
  internal/db/connection_test.go
  internal/testutils/test_helpers.go
Labels: enhancement

#41 bug: Update CD action
  .github/workflows/docker-publish.yml
Labels: enhancement

#42 update: run action on main not release
  .github/workflows/docker-publish.yml
Labels: enhancement

#43 feat: Update UpdateUser Handler to allow for updating is_onboarded
  internal/auth/auth_models/user.go
  internal/auth/auth_repositories/user_repo.go
Labels: bug
